### ISSUE TITLE
Guide internal review changes

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/draft-iguide-retry-timeout#44]
Requested changes following our internal guide internal review.

**Comment by aknguyen7** [comment]
1. Title: Failing fast and recovering from errors.

2. Description: Fail fast and recover when running into failures?

3. Retry and Timeout change to Timeout and Retry

4. What you'll learn
Explore how to use MicroProfile Timeout and Retry policies from the Fault Tolerance feature to make your microservice more resilient to common failures like network or IOException.
...
Finally, you'll explore the Retry policy and how it can help overcome temporarily intermittent failures your application may experience.
Timeout
In some cases, a user may experiences a page loading for a long time, only to never finish. 
Retry
Sometimes, the underlying issues may be short-lived. In these cases, rather than failing quickly on these transient failures, the Retry policy provides another chance for the request to succeed. Simply retrying the request may be all you need to avoid showing dreaded page.

5. Example: bank scenario
Imagine that you’re developing a microservice that allows bank clients to check their transaction history. Occasionally when a customer tries to view their transaction history, an unforeseen problem may prevent the data from loading and result in an indefinite page load.

Change overlay text to Indefinite page load. Please continue to the next step.

6. Adding the @Timeout annotation
Now that you’ve seen the page loads/loading? indefinitely due to a server side problem, let’s apply a Timeout policy to limit the time the request waits.

The @Timeout annotation takes an integer value that specifies the time in milliseconds allowed for the request to finish.

Optionally, the Timeout annotation can be configured to change the default time unit ...

value: The time allowed for the request to finish. The value must be greater than or equal to 0. 
A value of 0 means that Timeout policy is not applied. If the value is not specified, the default is 1000 milliseconds.

With a Timeout policy,  a TimeoutException occurs when the timeout value has elapsed.

Change the pink box error message to:
Your recent transactions are unavailable at this time. Please try again later.

7. Adding the @Retry annotation
After modifying the server.xml file to include the Fault Tolerance feature, and adding a Timeout policy to our sample application, the microservice fails with a TimeoutException if the request does not complete within 2000 milliseconds. Now, let's add a Retry policy to the code to retry the request to the transaction history microservice when a TimeoutException occurs.
