### ISSUE TITLE
Retry Timeout Playground

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/draft-iguide-retry-timeout#6]
Based on the params specified, timeline is created with the range 0 to `maxDuration` ~~with reasonably spaced divider ticks. There is a vertical line (current time marker) at 0.~~

~~3 buttons for user to interact with - `Success`, `Timeout Exception`, `<abortOn> Exception`~~

~~Upon running the code, the browser will show a loading page and the user may select one of the 3 buttons. (TODO: Assume first try fails? or allow user to pick?)~~
~~- `<abortOn> Exception` button selected at any time will kill the loading page and show the error page~~
~~- `Success` button selected at any time will show the transactions page~~
~~- `Timeout Exception` will keep the loading browser page, and advance the current time marker to the next retry on the timeline (based on delay/jitter)~~

~~During the advance animation, the current time marker will move, the browser loading page will be animated, and the buttons will be disabled as there is no current request.~~

~~When reaching the next request (retry), the current time marker will stop moving, the browser page will stop animating, and the buttons will be enabled.~~

**Comment by kevinwlau** [comment]
Yes, currently there is a lot of duplicate code in this effort to consolidate the playground code to a single widget. It is messy for now, but from a user's perspective, many of the refactoring and cleaning up changes will make no visible difference in the guide. Therefore, I'm deferring these to a later time after the primary guide deliverables have been finished.

These deferred changes will include:
- [ ] refactoring editor parsing methods into the playground.js
- [ ] addressing the (almost) duplicate `playground-dashboard.html`
- [ ] duplicate timeline code between `retry-timeout-playground.js` and `retry-timeout-callback.js`

**Comment by kevinwlau** [comment]
Edge cases:
- [ ] Using a single parentheses still passes. i.e. `@Timeout)` or `@Retry(`

**Comment by kevinwlau** [comment]
Unfinished code review items from #70 
- [ ]  When I initially got to the playground and selected 'Run' without any updates nothing happened. The console showed the following error because this.browser was undefined:
files.slack.com/files-pri/T27SFGS2W-FAWK51UUX/image.png
- [ ]  I misspelled a Retry parameter. In __verifyAndCorrectParms, retryParms is a empty object ({}), it is not null. Therefore, we went into all the conversion methods without any parameter being set. Then on line 1013, all those variables were null and null !== false so we didn't return. We then proceeded to the timeline with all default values. So, I think there is some logic errors in here somewhere.
- [ ]  Coding a parameter without a value is accepted (ie. @retry(delay)

**Comment by dmorgant** [comment]
- [ ] Prefill the URL since the first Run begins execution with nothing in the URL field.  May have to look at greying that out since you don't ever want the user to change the URL value or you will have to monitor if the URL is changed.
- [ ] With an upper limit of infinity set when the user codes maxDuration of 0, what should we do with the timeline?  Because the upper limit is so great the timeout and retry ticks are all on top of one another so you see no progress.  Perhaps leave the infinity upper limit, but code it as if the upper limit is (maxRetries * timeout * 1.5)?
- [ ]  Still need to do something with maxRetries set to 0 and maxDuration set to 0.  What should that be? An error message? 
- [ ]  The Refresh button on the sample browser is not working correctly.  Just the spinner starts up.  The timeline does nothing.
- [ ] I took out a value so it would use a default, but didn't take out the trailing comma from the value before.  I got a weird message: "TypeError: Cannot read property '1' of null".   Is that what you want?  Or do you want to just ignore the trailing comma?
- [ ] I executed the code to see the timeline in action on one of the Retry steps, then went to the playground to play with one of the values there.  The playground was showing the tick mark text next to the timeout and retry ticks.  So, somehow we did not get the correct setting for the step we are on when we went to it.

**Comment by dmorgant** [comment]
- [ ] Enable the refresh button in the browser to be consistent with the Jitter step in easily seeing the execution of the current values.  Must save current values off in case the user updated them, but had not yet hit RUN, prior to selecting the browser REFRESH.

**Comment by kevinwlau** [comment]
Playground development is complete, will move the refactoring work items into a new issue
